name: catis

services:
  catis:
    image: upmind/catis:latest
    restart: unless-stopped
    ports:
      - 9000:9000
    environment:
      # APP_CONTEXT: /catis
      MONGODB_URI: mongodb://mongo:27017/catis
      PLAY_APP_SECRET:
      AUTH_SIGNER_KEY:
      AUTH_CRYPTER_KEY:
    volumes:
      - ./application.conf:/app/conf/application.conf:ro
      - ./logs:/app/logs

  proxy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

  mongo:
    image: mongodb/mongodb-community-server:7.0.14-ubuntu2204
    restart: unless-stopped
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
  caddy_data:
  caddy_config:
